### ISSUE TITLE
Bug: the property 'VRAMSize' cannot be found on this object

### ISSUE THREAD

**Issue by simplenotsimpler** [matt9ucci/PSVBox#1]
Hi,

First of all, thank you. I really like the organization and layout of this project.

When I run the New-Machine function, I get an error:

SetValueInvocationException: E:\0-Sandbox\PSVBox\PSVBox\Machine.ps1:83:68
Line |
  83 |  … mSize) { [uint32]($VRamSize / 1MB) } else { $osType.RecommendedVRAM }
     |                                                ~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "VRAMSize": "The property 'VRAMSize' cannot be found on this object. Verify that the property exists and
     | can be set."

The machine still creates.

The fix:

From:
$m.VRAMSize = if ($VRamSize) { [uint32]($VRamSize / 1MB) } else { $osType.RecommendedVRAM }

To:
$m.graphicsAdapter.VRAMSize = if ($VRamSize) { [uint32]($VRamSize / 1MB) } else { $osType.RecommendedVRAM }

In https://www.virtualbox.org/sdkref/interface_i_machine.html, see:

readonly attribute IGraphicsAdapter | graphicsAdapter
-- | --
  | Graphics adapter object.  More...

I'm new to Git and GitHub so I don't feel comfortable with submitting a formal pull request.

Thank you.

**Comment by matt9ucci** [comment]
Thank you for your comment!

It is seemingly due to the breaking changes in 6.1 API. The [official doc](https://download.virtualbox.org/virtualbox/6.1.0/SDKRef.pdf) says:

> 14.1 Incompatible API changes with version 6.1
>   Split off the graphics adapter part of IMachine into IGraphicsAdapter. This moved 5 attributes.

I have fixed it by 46df9f0.

> I'm new to Git and GitHub so I don't feel comfortable with submitting a formal pull request.

It was no problem. Your kind and detailed comment helped me to find promptly the cause of this issue. Thank you 😄
